=== hmcts/cpp-context-prosecution-casefile-dlrm/pcfdlrm-domain/pcfdlrm-domain-event/src/main/resources/json/schema/pcfdlrm.events.material-added.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/prosecution/casefile/dlrm/domain/event/material-added",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "prosecutingAuthority": {
      "type": "string"
    },
    "prosecutorDefendantId": {
      "type": "string",
      "maxLength": 36
    },
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "defendantName": {
      "type": "string"
    },
    "material": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/dlrm/json/schemas/material.json"
    },
    "caseType": {
      "type": "string"
    },
    "documentTypeId": {
      "type": "string"
    },
    "documentType": {
      "type": "string"
    },
    "documentCategory": {
      "type": "string"
    },
    "isCpsCase": {
      "type": "boolean"
    },
    "cmsDocumentIdentifier": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/dlrm/json/schemas/cms-document-identifier.json"
    },
    "receivedDateTime": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "sectionCode": {
      "type": "string"
    }
  },
  "required": [
    "caseId",
    "material",
    "caseType"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile-dlrm/pcfdlrm-domain/pcfdlrm-domain-aggregate/src/test/resources/json/aggregate/material-added-defendant-level.json
{
  "caseId": "a4391799-f828-4515-a355-61f1d5d9690c",
  "caseType": "CC",
  "defendantId": "9824e40f-0289-4221-8854-346eb28c8f27",
  "defendantName": "Defendant Name",
  "documentCategory": "Defendant level",
  "documentType": "Private section - Judges & HMCTS",
  "documentTypeId": "d2d2d2d2-2222-4222-8222-222222222222",
  "isCpsCase": false,
  "material": {
    "documentType": "Private section - Judges & HMCTS",
    "fileCloudLocation": "azure/abc.pdf",
    "fileType": "99"
  },
  "prosecutorDefendantId": "9824e40f-0289-4221-8854-346eb28c8f27",
  "receivedDateTime": "EXCLUDED",
  "sectionCode": "PSJH"
}
